app:
    resource: "@AppBundle/Controller/"
    type:     annotation

users:
    type:     rest
    resource: AppBundle\Controller\API\v1\UsersController

contentpages:
    type:     rest
    resource: AppBundle\Controller\API\v1\ContentPagesController

batch:
    type:     rest
    resource: AppBundle\Controller\API\v1\BatchController

settings:
    type:     rest
    resource: AppBundle\Controller\API\v1\SettingsController
